name: Unit Testing
on: push

env:
  COMPOSER_ALLOW_SUPERUSER: 1
  MYSQL_ROOT_PASSWORD: ci
  MYSQL_DATABASE: ci
  MYSQL_USER: ci
  MYSQL_PASSWORD: ci

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]
    container:
      image: php:${{ matrix.php }}-alpine
    services:
      mysql:
        image:
          mysql:5.6
    steps:
      - name: Install APK Dependencies
        run: apk update && apk add git unzip mysql-client -q
      - name: Install PHP Extensions
        run: docker-php-ext-install pdo_mysql
      - name: Install Composer
        run: |
          wget -O installer https://getcomposer.org/installer
          php installer --install-dir=/usr/local/bin --filename=composer
      - name: Install Composer Libraries
        run: composer install --no-ansi
